backend:
  name: github
  repo: Mazinhh/Tech_Library
  branch: main

media_folder: "images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "data"
    label: "ملفات البيانات"
    files:
      - name: "termux"
        label: "أوامر Termux"
        file: "data/termux.json"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }
          - { label: "العنوان الفرعي", name: "subtitle", widget: "string" }
          - label: "مجموعات الأوامر"
            name: "groups"
            widget: "list"
            fields:
              - { label: "اسم المجموعة", name: "label", widget: "string" }
              - { label: "الأوامر", name: "cmds", widget: "list" }
      - name: "nano"
        label: "محرر Nano"
        file: "data/nano.json"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }
          - { label: "الوصف", name: "desc", widget: "string" }
          - { label: "المحتوى", name: "content", widget: "markdown" }
      - name: "dev"
        label: "خيارات المطور"
        file: "data/dev.json"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }
          - { label: "العنوان الفرعي", name: "subtitle", widget: "string" }
          - label: "التصنيفات"
            name: "categories"
            widget: "list"
            fields:
              - { label: "اسم التصنيف", name: "cat_title", widget: "string" }
              - label: "البطاقات"
                name: "cards"
                widget: "list"
                fields:
                  - { label: "العنوان", name: "summary", widget: "string" }
                  - { label: "الفائدة", name: "benefit", widget: "text" }
                  - { label: "التأثير", name: "effect", widget: "text", required: false }
                  - { label: "مستوى الخطورة", name: "safety", widget: "select", options: ["safe", "caution", "danger"] }
